management:
  endpoints:
    web:
      exposure:
        include: "*"

cds:
  sql.hana.search:
    fuzzy: true
    fuzzinessThreshold: 0.9
  security.mock.users:
    - name: rose
    - name: martha
      roles:
        - reviewer
    - name: amy
      roles:
        - processor
    - name: admin
      password: admin
      roles:
        - admin

  odata-v4:
    endpoint:
      path: "/"
  remote:
    services:
      "[API_EQUIPMENT]":
        model: "API_EQUIPMENT"
        destination:
          name: "MIT_S4"
        type: "odata-v2"
        http:
          suffix: "/sap/opu/odata/sap"
      Northwind:
        http:
          suffix: "/V4/Northwind/"
          service: "Northwind.svc"
        destination:
          properties:
            url: "https://services.odata.org"
        model: Northwind
        type: odata-v4
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
server:
  port: 4004
---
spring:
  config.activate.on-profile: cloud
cds:
  messaging.services:
    messaging:
      kind: enterprise-messaging
      enabled: true
      format: cloudevents
      publishPrefix: '$namespace/ce/'
      subscribePrefix: '$namespace/ce/'
