management:
    endpoints:
        web:
            exposure:
                include: "*"
---
spring:
    profiles: default
    web.resources.static-locations: "file:./app"
cds:
    security.mock.users:
    - name: rose
    - name: martha
      roles:
        - reviewer
    - name: amy
      roles:
        - processor
    - name: admin
      password: admin
      roles:
      - admin

    odata-v4:
        endpoint:
            path: "/"

server:
    port: 4004

---
spring:
    profiles: cloud

cds:
    security.authentication.authenticateMetadataEndpoints: false
    odata-v4:
        endpoint:
            path: "/"
