-- generated by csdl-to-sql for target hana_delta from travel-service-server.xml

create row table TravelService_xs_cache_partitions
(
    ClientID bigint not null,
    DeltaLink nvarchar(1000) null,
    PartitionSet nvarchar(128) not null,
    PartitionKey nvarchar(384) not null,
    ActiveEntityCount bigint not null,
    DeletedEntityCount bigint not null,
    CacheTimeoutSeconds integer not null,
    WaitedForSemaphore decimal(20,6) not null,
    LastRefreshOwner nvarchar(100) not null,
    LastRefreshStarted timestamp not null,
    LastRefreshFinished timestamp not null,
    LastRefreshDuration decimal(20,6) not null,
    LastRefreshStatus integer not null,
    LastRefreshError nvarchar(1000) null,
    NextRefreshScheduled timestamp not null,
    primary key (ClientID, PartitionSet, PartitionKey)
);

create row table TravelService_xs_client_languages
(
    LocaleID integer not null,
    LanguageTag nvarchar(50) not null,
    primary key (LanguageTag)
);

create unique index TravelService_xs_client_languages_locale_id_index on TravelService_xs_client_languages (LocaleID);

create row table TravelService_xs_client_expiry
(
    ClientID bigint not null,
    ExpiryTime timestamp not null,
    primary key (ClientID)
);

create row table TravelService_xs_hash_tracking
(
    QueryID bigint not null,
    KeyHash varbinary(64) not null,
    DataHash varbinary(64) not null,
    DeltaTime timestamp not null,
    primary key (QueryID, KeyHash)
);

create sequence TravelService_xs_key_tracking_id_seq start with 1 increment by 1 no cache;

create row table TravelService_xs_key_tracking
(
    TrackingID bigint not null,
    ClientID bigint not null,
    DeltaTime timestamp not null,
    DownloadSet nvarchar(250) not null,
    FilterText1 nvarchar(500) null,
    FilterText2 nclob null,
    CreatedCount integer not null,
    DeletedCount integer not null,
    UnzippedSize integer not null,
    ZippedSize integer not null,
    TrackingData1 varbinary(2000) null,
    TrackingData2 blob null,
    primary key (TrackingID)
);

create index TravelService_xs_key_tracking_client_id_index on TravelService_xs_key_tracking (ClientID);

create sequence TravelService_xs_query_tracking_id_seq start with 1 increment by 1 no cache;

create row table TravelService_xs_query_tracking
(
    QueryID bigint not null,
    ClientID bigint not null,
    QueryHash varbinary(64) not null,
    QueryText1 nvarchar(500) null,
    QueryText2 nclob null,
    primary key (QueryID)
);

create unique index TravelService_xs_query_tracking_query_hash_index on TravelService_xs_query_tracking (ClientID, QueryHash);

create column table TravelService_BookingStatus_cache
(
    locale_id integer not null,
    code nvarchar(1) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, code)
);

create column table TravelService_BookingStatus_texts_cache
(
    locale nvarchar(14) not null,
    code nvarchar(1) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, code)
);

create sequence TravelService_ClientRegistrationSet_id_seq start with 1 increment by 1 no cache;

create column table TravelService_ClientRegistrationSet
(
    ClientID bigint not null,
    AuthorizedUser nvarchar(200) null,
    ClientGUID nvarchar(36) not null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (ClientID)
);

create unique index TravelService_ClientRegistrationSet_guid_index on TravelService_ClientRegistrationSet (ClientGUID);

create column table TravelService_Countries_cache
(
    locale_id integer not null,
    code nvarchar(3) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, code)
);

create column table TravelService_Countries_texts_cache
(
    locale nvarchar(14) not null,
    code nvarchar(3) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, code)
);

create column table TravelService_Currencies_cache
(
    locale_id integer not null,
    code nvarchar(3) not null,
    descr nvarchar(1000) null,
    exponent integer null,
    minor nvarchar(500) null,
    minorUnit smallint null,
    name nvarchar(255) null,
    numcode integer null,
    symbol nvarchar(5) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, code)
);

create column table TravelService_Currencies_texts_cache
(
    locale nvarchar(14) not null,
    code nvarchar(3) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, code)
);

create column table TravelService_Customers_cache
(
    CustomerID nvarchar(100) not null,
    Address nvarchar(500) null,
    City nvarchar(500) null,
    CompanyName nvarchar(500) null,
    ContactName nvarchar(500) null,
    ContactTitle nvarchar(500) null,
    Country nvarchar(500) null,
    Fax nvarchar(500) null,
    Phone nvarchar(500) null,
    PostalCode nvarchar(500) null,
    Region nvarchar(500) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (CustomerID)
);

create column table TravelService_Employees_cache
(
    EmployeeID integer not null,
    Address nvarchar(500) null,
    BirthDate timestamp null,
    City nvarchar(500) null,
    Country nvarchar(500) null,
    Extension nvarchar(500) null,
    FirstName nvarchar(500) null,
    HireDate timestamp null,
    HomePhone nvarchar(500) null,
    LastName nvarchar(500) null,
    Notes nvarchar(500) null,
    PhotoPath nvarchar(500) null,
    PostalCode nvarchar(500) null,
    Region nvarchar(500) null,
    ReportsTo integer null,
    Title nvarchar(500) null,
    TitleOfCourtesy nvarchar(500) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (EmployeeID)
);

create column table TravelService_Orders_cache
(
    OrderID integer not null,
    CustomerID nvarchar(500) null,
    EmployeeID integer null,
    Freight decimal null,
    OrderDate timestamp null,
    RequiredDate timestamp null,
    ShipAddress nvarchar(500) null,
    ShipCity nvarchar(500) null,
    ShipCountry nvarchar(500) null,
    ShipName nvarchar(500) null,
    ShipPostalCode nvarchar(500) null,
    ShipRegion nvarchar(500) null,
    ShipVia integer null,
    ShippedDate timestamp null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (OrderID)
);

create column table TravelService_Supplement_cache
(
    locale_id integer not null,
    SupplementID nvarchar(10) not null,
    CurrencyCode_code nvarchar(3) null,
    Description nvarchar(1024) null,
    LastChangedAt timestamp null,
    LastChangedBy nvarchar(255) null,
    Price decimal(16,3) null,
    Type_code nvarchar(2) null,
    createdAt timestamp null,
    createdBy nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, SupplementID)
);

create column table TravelService_SupplementType_cache
(
    locale_id integer not null,
    code nvarchar(2) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, code)
);

create column table TravelService_SupplementType_texts_cache
(
    locale nvarchar(14) not null,
    code nvarchar(2) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, code)
);

create column table TravelService_Supplement_texts_cache
(
    locale nvarchar(14) not null,
    SupplementID nvarchar(10) not null,
    Description nvarchar(1024) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, SupplementID)
);

create column table TravelService_TravelStatus_cache
(
    locale_id integer not null,
    code nvarchar(1) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale_id, code)
);

create column table TravelService_TravelStatus_texts_cache
(
    locale nvarchar(14) not null,
    code nvarchar(1) not null,
    descr nvarchar(1000) null,
    name nvarchar(255) null,
    is_deleted boolean not null,
    last_modified timestamp not null,
    primary key (locale, code)
);

create sequence TravelService_xs_data_metrics_id_seq start with 1 increment by 1 no cache;

create column table TravelService_xs_data_metrics
(
    _id bigint not null,
    _start timestamp not null,
    _period decimal(20,0) not null,
    _process nvarchar(100) not null,
    _tenant nvarchar(200) null,
    _provider nvarchar(100) not null,
    _component nvarchar(200) not null,
    _metric nvarchar(100) not null,
    _unit nvarchar(50) not null,
    _count bigint null,
    _sum bigint null,
    _average decimal null,
    _minimum bigint null,
    _maximum bigint null,
    primary key (_id)
);

create row table TravelService_xs_repeatability_log
(
    CreationTime timestamp not null,
    ResponseStatus smallint not null,
    ClientID varbinary(100) not null,
    RequestID varbinary(100) not null,
    ContentID varbinary(100) not null,
    ResponseHeaders nvarchar(1000) not null,
    ResponseData1 varbinary(2000) null,
    ResponseData2 blob null,
    primary key (RequestID, ContentID)
);

create index TravelService_xs_repeatability_log_client_id_index on TravelService_xs_repeatability_log (ClientID);

create index TravelService_xs_repeatability_log_creation_time_index on TravelService_xs_repeatability_log (CreationTime);

create index TravelService_Supplement_cache_rc_CurrencyCode on TravelService_Supplement_cache (CurrencyCode_code);

create index TravelService_Supplement_cache_rc_Type on TravelService_Supplement_cache (Type_code);

-------------------------------------------------------------------------------
-- tracking tables
-------------------------------------------------------------------------------

create column table sap_fe_cap_travel_Airline_tracking
(
    AirlineID NVARCHAR(3) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (AirlineID)
);

create column table sap_fe_cap_travel_Airport_tracking
(
    AirportID NVARCHAR(3) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (AirportID)
);

create column table sap_fe_cap_travel_Booking_tracking
(
    BookingUUID NVARCHAR(36) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (BookingUUID)
);

create column table sap_fe_cap_travel_BookingSupplement_tracking
(
    BookSupplUUID NVARCHAR(36) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (BookSupplUUID)
);

create column table sap_cache_equipment_Equipment_tracking
(
    Equipment NVARCHAR(18) not null,
    ValidityEndDate DATE not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (Equipment, ValidityEndDate)
);

create column table sap_fe_cap_travel_Flight_tracking
(
    AirlineID NVARCHAR(3) not null,
    FlightDate DATE not null,
    ConnectionID NVARCHAR(4) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (AirlineID, FlightDate, ConnectionID)
);

create column table sap_fe_cap_travel_FlightConnection_tracking
(
    ConnectionID NVARCHAR(4) not null,
    AirlineID NVARCHAR(3) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (ConnectionID, AirlineID)
);

create column table sap_fe_cap_travel_Passenger_tracking
(
    CustomerID NVARCHAR(6) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (CustomerID)
);

create column table sap_fe_cap_travel_Travel_tracking
(
    TravelUUID NVARCHAR(36) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (TravelUUID)
);

create column table sap_fe_cap_travel_TravelAgency_tracking
(
    AgencyID NVARCHAR(6) not null,
    last_modified timestamp not null,
    is_deleted boolean not null,
    primary key (AgencyID)
);

-------------------------------------------------------------------------------
-- tracking triggers
-------------------------------------------------------------------------------

create trigger sap_fe_cap_travel_Airline_insert_tracking
    after insert on sap_fe_cap_travel_Airline
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Airline_tracking (AirlineID, last_modified, is_deleted)
        values (:newrow.AirlineID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Airline_update_tracking
    after update on sap_fe_cap_travel_Airline
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Airline_tracking (AirlineID, last_modified, is_deleted)
        values (:newrow.AirlineID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Airline_delete_tracking
    after delete on sap_fe_cap_travel_Airline
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Airline_tracking (AirlineID, last_modified, is_deleted)
        values (:oldrow.AirlineID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_Airport_insert_tracking
    after insert on sap_fe_cap_travel_Airport
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Airport_tracking (AirportID, last_modified, is_deleted)
        values (:newrow.AirportID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Airport_update_tracking
    after update on sap_fe_cap_travel_Airport
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Airport_tracking (AirportID, last_modified, is_deleted)
        values (:newrow.AirportID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Airport_delete_tracking
    after delete on sap_fe_cap_travel_Airport
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Airport_tracking (AirportID, last_modified, is_deleted)
        values (:oldrow.AirportID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_Booking_insert_tracking
    after insert on sap_fe_cap_travel_Booking
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Booking_tracking (BookingUUID, last_modified, is_deleted)
        values (:newrow.BookingUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Booking_update_tracking
    after update on sap_fe_cap_travel_Booking
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Booking_tracking (BookingUUID, last_modified, is_deleted)
        values (:newrow.BookingUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Booking_delete_tracking
    after delete on sap_fe_cap_travel_Booking
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Booking_tracking (BookingUUID, last_modified, is_deleted)
        values (:oldrow.BookingUUID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_BookingSupplement_insert_tracking
    after insert on sap_fe_cap_travel_BookingSupplement
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_BookingSupplement_tracking (BookSupplUUID, last_modified, is_deleted)
        values (:newrow.BookSupplUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_BookingSupplement_update_tracking
    after update on sap_fe_cap_travel_BookingSupplement
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_BookingSupplement_tracking (BookSupplUUID, last_modified, is_deleted)
        values (:newrow.BookSupplUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_BookingSupplement_delete_tracking
    after delete on sap_fe_cap_travel_BookingSupplement
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_BookingSupplement_tracking (BookSupplUUID, last_modified, is_deleted)
        values (:oldrow.BookSupplUUID, current_utctimestamp, true) with primary key;
end;

create trigger sap_cache_equipment_Equipment_insert_tracking
    after insert on sap_cache_equipment_Equipment
    referencing new row newrow
    for each row
begin
    upsert sap_cache_equipment_Equipment_tracking (Equipment, ValidityEndDate, last_modified, is_deleted)
        values (:newrow.Equipment, :newrow.ValidityEndDate, current_utctimestamp, false) with primary key;
end;

create trigger sap_cache_equipment_Equipment_update_tracking
    after update on sap_cache_equipment_Equipment
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_cache_equipment_Equipment_tracking (Equipment, ValidityEndDate, last_modified, is_deleted)
        values (:newrow.Equipment, :newrow.ValidityEndDate, current_utctimestamp, false) with primary key;
end;

create trigger sap_cache_equipment_Equipment_delete_tracking
    after delete on sap_cache_equipment_Equipment
    referencing old row oldrow
    for each row
begin
    upsert sap_cache_equipment_Equipment_tracking (Equipment, ValidityEndDate, last_modified, is_deleted)
        values (:oldrow.Equipment, :oldrow.ValidityEndDate, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_Flight_insert_tracking
    after insert on sap_fe_cap_travel_Flight
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Flight_tracking (AirlineID, FlightDate, ConnectionID, last_modified, is_deleted)
        values (:newrow.AirlineID, :newrow.FlightDate, :newrow.ConnectionID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Flight_update_tracking
    after update on sap_fe_cap_travel_Flight
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Flight_tracking (AirlineID, FlightDate, ConnectionID, last_modified, is_deleted)
        values (:newrow.AirlineID, :newrow.FlightDate, :newrow.ConnectionID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Flight_delete_tracking
    after delete on sap_fe_cap_travel_Flight
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Flight_tracking (AirlineID, FlightDate, ConnectionID, last_modified, is_deleted)
        values (:oldrow.AirlineID, :oldrow.FlightDate, :oldrow.ConnectionID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_FlightConnection_insert_tracking
    after insert on sap_fe_cap_travel_FlightConnection
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_FlightConnection_tracking (ConnectionID, AirlineID, last_modified, is_deleted)
        values (:newrow.ConnectionID, :newrow.AirlineID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_FlightConnection_update_tracking
    after update on sap_fe_cap_travel_FlightConnection
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_FlightConnection_tracking (ConnectionID, AirlineID, last_modified, is_deleted)
        values (:newrow.ConnectionID, :newrow.AirlineID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_FlightConnection_delete_tracking
    after delete on sap_fe_cap_travel_FlightConnection
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_FlightConnection_tracking (ConnectionID, AirlineID, last_modified, is_deleted)
        values (:oldrow.ConnectionID, :oldrow.AirlineID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_Passenger_insert_tracking
    after insert on sap_fe_cap_travel_Passenger
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Passenger_tracking (CustomerID, last_modified, is_deleted)
        values (:newrow.CustomerID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Passenger_update_tracking
    after update on sap_fe_cap_travel_Passenger
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Passenger_tracking (CustomerID, last_modified, is_deleted)
        values (:newrow.CustomerID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Passenger_delete_tracking
    after delete on sap_fe_cap_travel_Passenger
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Passenger_tracking (CustomerID, last_modified, is_deleted)
        values (:oldrow.CustomerID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_Travel_insert_tracking
    after insert on sap_fe_cap_travel_Travel
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_Travel_tracking (TravelUUID, last_modified, is_deleted)
        values (:newrow.TravelUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Travel_update_tracking
    after update on sap_fe_cap_travel_Travel
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Travel_tracking (TravelUUID, last_modified, is_deleted)
        values (:newrow.TravelUUID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_Travel_delete_tracking
    after delete on sap_fe_cap_travel_Travel
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_Travel_tracking (TravelUUID, last_modified, is_deleted)
        values (:oldrow.TravelUUID, current_utctimestamp, true) with primary key;
end;

create trigger sap_fe_cap_travel_TravelAgency_insert_tracking
    after insert on sap_fe_cap_travel_TravelAgency
    referencing new row newrow
    for each row
begin
    upsert sap_fe_cap_travel_TravelAgency_tracking (AgencyID, last_modified, is_deleted)
        values (:newrow.AgencyID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_TravelAgency_update_tracking
    after update on sap_fe_cap_travel_TravelAgency
    referencing new row newrow, old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_TravelAgency_tracking (AgencyID, last_modified, is_deleted)
        values (:newrow.AgencyID, current_utctimestamp, false) with primary key;
end;

create trigger sap_fe_cap_travel_TravelAgency_delete_tracking
    after delete on sap_fe_cap_travel_TravelAgency
    referencing old row oldrow
    for each row
begin
    upsert sap_fe_cap_travel_TravelAgency_tracking (AgencyID, last_modified, is_deleted)
        values (:oldrow.AgencyID, current_utctimestamp, true) with primary key;
end;

-------------------------------------------------------------------------------
-- delta views
-------------------------------------------------------------------------------

create view TravelService_Airline_delta as
select
    t.AirlineID,
    d.AirlinePicURL,
    d.CurrencyCode_code,
    d.Name,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Airline_tracking t
    left outer join TravelService_Airline d on d.AirlineID = t.AirlineID;

create view TravelService_Airport_delta as
select
    t.AirportID,
    d.City,
    d.CountryCode_code,
    d.Name,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Airport_tracking t
    left outer join TravelService_Airport d on d.AirportID = t.AirportID;

create view TravelService_Booking_delta as
select
    t.BookingUUID,
    d.BookingDate,
    d.BookingID,
    d.BookingStatus_code,
    d.ConnectionID,
    d.CurrencyCode_code,
    d.FlightDate,
    d.FlightPrice,
    d.LastChangedAt,
    d.LastChangedBy,
    d.createdAt,
    d.createdBy,
    d.to_Carrier_AirlineID,
    d.to_Customer_CustomerID,
    d.to_Travel_TravelUUID,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Booking_tracking t
    left outer join TravelService_Booking d on d.BookingUUID = t.BookingUUID;

create view TravelService_BookingSupplement_delta as
select
    t.BookSupplUUID,
    d.BookingSupplementID,
    d.CurrencyCode_code,
    d.LastChangedAt,
    d.LastChangedBy,
    d.Price,
    d.createdAt,
    d.createdBy,
    d.to_Booking_BookingUUID,
    d.to_Supplement_SupplementID,
    d.to_Travel_TravelUUID,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_BookingSupplement_tracking t
    left outer join TravelService_BookingSupplement d on d.BookSupplUUID = t.BookSupplUUID;

create view TravelService_Equipment_delta as
select
    t.Equipment,
    t.ValidityEndDate,
    d.ABCIndicator,
    d.AcquisitionDate,
    d.AcquisitionValue,
    d.AssetLocation,
    d.AssetManufacturerName,
    d.AssetRoom,
    d.AuthorizationGroup,
    d.Building,
    d.BusinessArea,
    d.BusinessPartnerName1,
    d.BusinessPartnerName2,
    d.CatalogProfile,
    d.CityName,
    d.CompanyCode,
    d.ConstructionMaterial,
    d.ConstructionMonth,
    d.ConstructionYear,
    d.ControllingArea,
    d.CostCenter,
    d.Country,
    d.CreatedByUser,
    d.CreationDate,
    d.Currency,
    d.DistributionChannel,
    d.EquipHasSubOrdinateEquipment,
    d.EquipInstallationPositionNmbr,
    d.EquipIsAllocToSuperiorEquip,
    d.EquipUsagePeriodSequenceNumber,
    d.EquipmentCategory,
    d.EquipmentEndOfUseDate,
    d.EquipmentIsAssignedToDelivery,
    d.EquipmentIsAtCustomer,
    d.EquipmentIsAvailable,
    d.EquipmentIsInWarehouse,
    d.EquipmentIsInactive,
    d.EquipmentIsInstalled,
    d.EquipmentIsMarkedForDeletion,
    d.EquipmentName,
    d.EquipmentOID,
    d.EquipmentValidityEndDateTime,
    d.FaxNumber,
    d.FixedAsset,
    d.Floor,
    d.FormOfAddress,
    d.FunctionalLocation,
    d.FunctionalLocationLabelName,
    d.FunctionalLocationName,
    d.GrossWeight,
    d.GrossWeightUnit,
    d.HouseNumber,
    d.HouseNumberSupplementText,
    d.InventoryNumber,
    d.LastChangeDateTime,
    d.LastChangedByUser,
    d.MainWorkCenter,
    d.MainWorkCenterInternalID,
    d.MainWorkCenterPlant,
    d.MaintObjectFreeDefinedAttrib,
    d.MaintObjectInternalID,
    d.MaintObjectLocAcctAssgmtNmbr,
    d.MaintenancePlan,
    d.MaintenancePlannerGroup,
    d.MaintenancePlanningPlant,
    d.MaintenancePlant,
    d.ManufacturerCountry,
    d.ManufacturerPartNmbr,
    d.ManufacturerPartTypeName,
    d.ManufacturerSerialNumber,
    d.MasterFixedAsset,
    d.Material,
    d.MeasuringPoint,
    d.NextEquipUsagePeriodSqncNmbr,
    d.OperationStartDate,
    d.OrganizationDivision,
    d.PhoneNumber,
    d.PlantSection,
    d.PostalCode,
    d.Region,
    d.RoomNumber,
    d.SalesGroup,
    d.SalesOffice,
    d.SalesOrganization,
    d.SerialNumber,
    d.SettlementOrder,
    d.SizeOrDimensionText,
    d.StreetName,
    d.SuperordinateEquipment,
    d.TechnicalObjectSortCode,
    d.TechnicalObjectType,
    d.UniqueItemIdentifier,
    d.UniqueItemIdentifierRespPlant,
    d.UniqueItemIdentifierStrucType,
    d.ValidityEndTime,
    d.ValidityStartDate,
    d.WBSElementExternalID,
    d.WorkCenter,
    d.WorkCenterInternalID,
    d.WorkCenterPlant,
    t.is_deleted,
    t.last_modified
from sap_cache_equipment_Equipment_tracking t
    left outer join TravelService_Equipment d on d.Equipment = t.Equipment and d.ValidityEndDate = t.ValidityEndDate;

create view TravelService_Flight_delta as
select
    t.AirlineID,
    t.FlightDate,
    t.ConnectionID,
    d.CurrencyCode_code,
    d.MaximumSeats,
    d.OccupiedSeats,
    d.PlaneType,
    d.Price,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Flight_tracking t
    left outer join TravelService_Flight d on d.AirlineID = t.AirlineID and d.FlightDate = t.FlightDate and d.ConnectionID = t.ConnectionID;

create view TravelService_FlightConnection_delta as
select
    t.ConnectionID,
    t.AirlineID,
    d.ArrivalTime,
    d.DepartureAirport_AirportID,
    d.DepartureTime,
    d.DestinationAirport_AirportID,
    d.Distance,
    d.DistanceUnit,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_FlightConnection_tracking t
    left outer join TravelService_FlightConnection d on d.ConnectionID = t.ConnectionID and d.AirlineID = t.AirlineID;

create view TravelService_Passenger_delta as
select
    t.CustomerID,
    d.City,
    d.CountryCode_code,
    d.EMailAddress,
    d.FirstName,
    d.LastChangedAt,
    d.LastChangedBy,
    d.LastName,
    d.PhoneNumber,
    d.PostalCode,
    d.Street,
    d.Title,
    d.createdAt,
    d.createdBy,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Passenger_tracking t
    left outer join TravelService_Passenger d on d.CustomerID = t.CustomerID;

create view TravelService_Travel_delta as
select
    t.TravelUUID,
    d.BeginDate,
    d.BookingFee,
    d.CurrencyCode_code,
    d.Description,
    d.EndDate,
    d.GoGreen,
    d.GreenFee,
    d.LastChangedAt,
    d.LastChangedBy,
    d.TotalPrice,
    d.TravelID,
    d.TravelStatus_code,
    d.TreesPlanted,
    d.createdAt,
    d.createdBy,
    d.to_Agency_AgencyID,
    d.to_Customer_CustomerID,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_Travel_tracking t
    left outer join TravelService_Travel d on d.TravelUUID = t.TravelUUID;

create view TravelService_TravelAgency_delta as
select
    t.AgencyID,
    d.City,
    d.CountryCode_code,
    d.EMailAddress,
    d.Name,
    d.PhoneNumber,
    d.PostalCode,
    d.Street,
    d.WebAddress,
    t.is_deleted,
    t.last_modified
from sap_fe_cap_travel_TravelAgency_tracking t
    left outer join TravelService_TravelAgency d on d.AgencyID = t.AgencyID;

-------------------------------------------------------------------------------
-- tracking initialization
-------------------------------------------------------------------------------

upsert sap_fe_cap_travel_Airline_tracking (AirlineID, last_modified, is_deleted)
    select AirlineID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Airline;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Airline_tracking)

upsert sap_fe_cap_travel_Airport_tracking (AirportID, last_modified, is_deleted)
    select AirportID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Airport;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Airport_tracking)

upsert sap_fe_cap_travel_Booking_tracking (BookingUUID, last_modified, is_deleted)
    select BookingUUID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Booking;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Booking_tracking)

upsert sap_fe_cap_travel_BookingSupplement_tracking (BookSupplUUID, last_modified, is_deleted)
    select BookSupplUUID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_BookingSupplement;
    -- if not exists (select top 1 true from sap_fe_cap_travel_BookingSupplement_tracking)

upsert sap_cache_equipment_Equipment_tracking (Equipment, ValidityEndDate, last_modified, is_deleted)
    select Equipment, ValidityEndDate, current_utctimestamp as last_modified, false as is_deleted from sap_cache_equipment_Equipment;
    -- if not exists (select top 1 true from sap_cache_equipment_Equipment_tracking)

upsert sap_fe_cap_travel_Flight_tracking (AirlineID, FlightDate, ConnectionID, last_modified, is_deleted)
    select AirlineID, FlightDate, ConnectionID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Flight;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Flight_tracking)

upsert sap_fe_cap_travel_FlightConnection_tracking (ConnectionID, AirlineID, last_modified, is_deleted)
    select ConnectionID, AirlineID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_FlightConnection;
    -- if not exists (select top 1 true from sap_fe_cap_travel_FlightConnection_tracking)

upsert sap_fe_cap_travel_Passenger_tracking (CustomerID, last_modified, is_deleted)
    select CustomerID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Passenger;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Passenger_tracking)

upsert sap_fe_cap_travel_Travel_tracking (TravelUUID, last_modified, is_deleted)
    select TravelUUID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_Travel;
    -- if not exists (select top 1 true from sap_fe_cap_travel_Travel_tracking)

upsert sap_fe_cap_travel_TravelAgency_tracking (AgencyID, last_modified, is_deleted)
    select AgencyID, current_utctimestamp as last_modified, false as is_deleted from sap_fe_cap_travel_TravelAgency;
    -- if not exists (select top 1 true from sap_fe_cap_travel_TravelAgency_tracking)
